### ISSUE TITLE
image URIs are not recognized by `org-display-inline-images`

### ISSUE THREAD

**Issue by repelliuss** [LaurenceWarne/finito.el#2]
README:
> if org-display-remote-inline-images is set, then finito will defer remote image handling to org

`org-display-inline-image` documentation:
> An inline image is a link which follows either of these
> conventions:
> 
>   1. Its path is a file with an extension matching return value
>      from image-file-name-regexp and it has no contents.
> 
>   2. Its description consists in a single link of the previous
>      type.  In this case, that link must be a well-formed plain
>      or angle link, i.e., it must have an explicit "file" type.

According to the documentation, org won't recognize inserted URIs. It works when I suffix them with one of jpg, jpeg and png and I can still browse them in my browser. I suppose you can put one of those to each URI without a problem(?),  no matter the real extension.

I am also skeptic about usage of `org-display-remote-inline-images`. I don't want to disable it for a package as it will affect my other documents.

What do you think about those?

**Comment by LaurenceWarne** [comment]
> According to the documentation, org won't recognize inserted URIs.

I thought it would looking at https://blog.tecosaur.com/tmio/2021-04-26-Welcome.html#inline-display-remote (possibly related: https://www.reddit.com/r/orgmode/comments/p4ii75/orgdisplayremoteinlineimages_is_not_working/? - I'm on org 9.4.6 also), but yes experimentally Ican't get `org-display-remote-inline-images` to have the effect described in that post.

> I am also skeptic about usage of org-display-remote-inline-images. I don't want to disable it for a package as it will affect my other documents.

 I'm all for removing the "interop" altogether, ie ignoring `org-display-remote-inline-images` and always creating a cache.  I don't think I really understand the usage of `org-display-remote-inline-images` and I can't find any documentation around it.  Would this solve your problem?

**Comment by repelliuss** [comment]
The link in the post is in the form of, `[[https://github.com/larsmagne/meme/raw/master/images/Grandma-Finds-The-Internet.jpg]]` which doesn't have a description part and also matches a value from `image-file-name-regexp` which is `jpg` so it conforms case 1. I can properly view this remote image via the org link when `org-display-remote-inline-images` is set to `download` or `cache`. It seems like for remote images any link should match `image-file-name-regexp`.

Finito seems to put `[[https://books.google.com/books/content?id=5NomkK4EV68C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api]]` links similar to this. There is no way for org to know that they are actually images. But when I blindly put `.jpeg`, `[[https://books.google.com/books/content?id=5NomkK4EV68C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api.jpeg]]`, org displays it.

It seems like what you put doesn't matter. Well, it is a hack but I couldn't find any downsides yet. What you do is duplicated functionality, though yours seem faster as you get them in parallel so I prefer it except having `org-display-remote-inline-images` set to `skip`. It would solve my problem.

**Comment by LaurenceWarne** [comment]
> The link in the post is in the form of, [[https://github.com/larsmagne/meme/raw/master/images/Grandma-Finds-The-Internet.jpg]] which doesn't have a description part and also matches a value from image-file-name-regexp which is jpg so it conforms case 1. 

Strange, for me even `[[https://github.com/larsmagne/meme/raw/master/images/Grandma-Finds-The-Internet.jpg]]` `org-display-inline-images` does not display the image, but I guess that's unrelated if it's functional for you :slightly_smiling_face: 

> It seems like what you put doesn't matter. Well, it is a hack but I couldn't find any downsides yet. What you do is duplicated functionality, though yours seem faster as you get them in parallel so I prefer it except having org-display-remote-inline-images set to skip. It would solve my problem.

So if there was an option along the lines of `finito-respect-org-display-remote-inline-images` which would ignore `org-display-remote-inline-images` if `nil`, would that allow you the flexibility you're looking for (from what I gather having `org-display-remote-inline-images` as `cache`/`download` but letting finito manage its own cache)?

**Comment by repelliuss** [comment]
yeah, if you agree

**Comment by LaurenceWarne** [comment]
> Well, it is a hack but I couldn't find any downsides yet. 

fyi, you can perform this hack using the customization options also, I think something like this would be equivalent:
```elisp
(defclass my-book-writer (finito-book-writer)
  nil
  "My class for writing book information to a buffer.")

(cl-defmethod finito-insert-image ((_ finito-book-writer) image)
  "Insert IMAGE (an image file name) into the current buffer."
  (insert "[[" (if (f-ext-p image) image (s-append ".jpg" image)) "]]  "))

(setq finito-writer-instance (my-book-writer))
```
Though I'm guessing you're already doing something similar :slightly_smiling_face:

**Comment by LaurenceWarne** [comment]
Oops, closed this by accident

> yeah, if you agree

Yeah I'm fine with it, I don't think it would be difficult to implement - I can probably start on it tommorrow

**Comment by repelliuss** [comment]
> fyi, you can perform this hack using the customization options also, I think something like this would:

Yes, it works and I can say that your method seems to be less blocking. If you could reproduce the behaviour, I would suggest you test it and even reduce `finito-respect-org-display-remote-inline-images` to `finito-include-images` though it is not a big deal. The problem was having users initially `org-display-remote-inline-images` being set other than `skip` and them not seeing images at first, which might be confusing, and forcing them to `skip`.

**Comment by LaurenceWarne** [comment]
I've added a new custom option `finitio-use-image-uris` in https://github.com/LaurenceWarne/finito.el/commit/7d8880fea27baf516a7233c2e2c36ebd671bf6cd.  It defaults to `nil`, so that by default finito will always create an image cache + insert images as local files regardless of the value of `org-display-remote-inline-images`.  I think this is nicer and more flexible, let me know what you think and if you encounter any issues.

**Comment by repelliuss** [comment]
Yes, thank you!

**Comment by LaurenceWarne** [comment]
No problem!  Thanks for raising this
